services:
  - type: web
    name: flask-webhook
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: TOKEN
        value: your_token_here
      - key: OWNER
        value: your_owner_here
