name: Ads Scheduler

on:
  workflow_dispatch:
  
jobs:
  post-ad:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: IDK
        env: 
            REPO_VAR_1: ${{ vars.AD_1}}
            URLS: ${{ vars.DISCORD_URLS}}
            TOKEN_SCRT_1: ${{ secrets.ACCOUNT_1_TOKEN}}
            
        run: |
          python3 1.py 

      
       
